export const SLOT_ABI = [
  { type: "function", name: "placeBet", stateMutability: "payable", inputs: [], outputs: [{ name: "id", type: "uint256" }] },
  { type: "function", name: "fund", stateMutability: "payable", inputs: [], outputs: [] },
  { type: "function", name: "withdrawPayout", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "owed", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "settle", stateMutability: "nonpayable", inputs: [{ name: "id", type: "uint256" }], outputs: [] },
  { type: "function", name: "maxBet", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "minBet", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "bankroll", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "canSettle", stateMutability: "view", inputs: [{ name: "id", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "paused", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "spins", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [
    { name: "player", type: "address" }, { name: "amount", type: "uint96" }, { name: "targetBlock", type: "uint64" }, { name: "settled", type: "bool" }] },
  { type: "event", name: "SpinPlaced", inputs: [
    { name: "id", type: "uint256", indexed: true }, { name: "player", type: "address", indexed: true },
    { name: "amount", type: "uint256", indexed: false }, { name: "targetBlock", type: "uint256", indexed: false }] },
  { type: "event", name: "SpinSettled", inputs: [
    { name: "id", type: "uint256", indexed: true }, { name: "player", type: "address", indexed: true },
    { name: "amount", type: "uint256", indexed: false }, { name: "r0", type: "uint8", indexed: false },
    { name: "r1", type: "uint8", indexed: false }, { name: "r2", type: "uint8", indexed: false },
    { name: "payout", type: "uint256", indexed: false }] },
  { type: "event", name: "SpinExpired", inputs: [
    { name: "id", type: "uint256", indexed: true }, { name: "player", type: "address", indexed: true },
    { name: "amount", type: "uint256", indexed: false }] },
  { type: "error", name: "BetTooSmall", inputs: [] },
  { type: "error", name: "BetTooLarge", inputs: [] },
  { type: "error", name: "TooEarly", inputs: [] },
  { type: "error", name: "AlreadySettled", inputs: [] },
  { type: "error", name: "UnknownSpin", inputs: [] },
  { type: "error", name: "InsufficientUnlocked", inputs: [] },
  { type: "error", name: "BadLimits", inputs: [] },
  { type: "error", name: "RenounceDisabled", inputs: [] },
  { type: "error", name: "NothingOwed", inputs: [] },
  { type: "error", name: "SendFailed", inputs: [] },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "SafeERC20FailedOperation", inputs: [{ name: "token", type: "address" }] },
] as const;

